# ──────────────────────────────────────────────────────────────────────────────
# NGINX App Protect Log Configuration
# Logs all illegal (blocked/alarmed) requests — one per namespace.
# ──────────────────────────────────────────────────────────────────────────────
apiVersion: appprotect.f5.com/v1beta1
kind: APLogConf
metadata:
  name: waf-logconf
  namespace: cine
spec:
  content:
    format: default
    max_request_size: any
    max_message_size: 64k
  filter:
    request_type: illegal
---
apiVersion: appprotect.f5.com/v1beta1
kind: APLogConf
metadata:
  name: waf-logconf
  namespace: cine-tmdb
spec:
  content:
    format: default
    max_request_size: any
    max_message_size: 64k
  filter:
    request_type: illegal
