apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: cine-tmdb
  namespace: cine-tmdb
  annotations:
    # NGINX Plus IC WAF â€” APPolicy + log in same namespace
    nginx.org/app-protect-policy: "waf-policy"
    nginx.org/app-protect-security-log-enable: "true"
    nginx.org/app-protect-security-log: "waf-logconf"
    nginx.org/app-protect-security-log-destination: "syslog:server=127.0.0.1:514"
spec:
  ingressClassName: nginx
  rules:
    - host: cine-tmdb.example.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: cine-tmdb
                port:
                  number: 80
